package com.xworkz.collections.constant;

public enum Type {
	HIERARCHICAL_DATABASES,
	NETWORK_DATABASES,
	OBJECT_ORIENTED_DATABASES,
	RELATIONAL_DATABASES,SQL_DATABASE,NO_SQL_DATABASE,
	NOSQL_DATABASES;
}
